const data = {
  products: [
    {
      name: 'Nike Shirt',
      category: 'Shirts',
      image: '/images/shirts1.jpg',
      price: 70,
      brand: 'Nike',
      ranting: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Adidas Shirt',
      category: 'Shirts',
      image: '/images/shirts2.jpg',
      price: 80,
      brand: 'Adidas',
      ranting: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Puma Shirt',
      category: 'Shirts',
      image: '/images/shirts3.jpg',
      price: 90,
      brand: 'Puma',
      ranting: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Nike Shoes',
      category: 'Shoes',
      image: '/images/Shoes1.jpg',
      price: 90,
      brand: 'Nike',
      ranting: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking Shoes',
    },
    {
      name: 'Adidas Shoes',
      category: 'Shoes',
      image: '/images/Shoes2.jpg',
      price: 95,
      brand: 'Adidas',
      ranting: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shoes',
    },
    {
      name: 'Puma Shoes',
      category: 'Shoes',
      image: '/images/Shoes3.jpg',
      price: 75,
      brand: 'Puma',
      ranting: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shoes',
    },
  ],
};
export default data;
